default_language_version:
  python: python3.11
exclude: .*migrations\/.*
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
            exclude: 'client/package*.json|poetry.lock'
        -   id: check-builtin-literals
        -   id: check-toml
        -   id: check-merge-conflict

    -   repo: https://github.com/pycqa/isort
        rev: 5.12.0
        hooks:
        -   id: isort
            name: isort (python)

    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.10.1
        hooks:
        -   id: pyupgrade

    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.0.286
        hooks:
          - id: ruff
            exclude: 'migrations/'
#            args: [ --fix, --exit-non-zero-on-fix ]

    -   repo: https://github.com/Riverside-Healthcare/djLint
        rev: v1.32.1
        hooks:
          - id: djlint-django
