# Generated by Django 4.2.7 on 2023-11-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=50, verbose_name='nginx instruction')),
                ('argument', models.CharField(blank=True, max_length=100, verbose_name='nginx instruction argument')),
            ],
            options={
                'verbose_name': 'Nginx Instruction',
                'verbose_name_plural': 'Nginx Instructions',
                'ordering': ['instruction'],
                'unique_together': {('instruction', 'argument')},
            },
        ),
        migrations.CreateModel(
            name='NginxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='conf name')),
                ('value', models.TextField(verbose_name='conf value')),
            ],
            options={
                'verbose_name': 'Nginx Configuration',
                'verbose_name_plural': 'Nginx Configurations',
                'ordering': ['name'],
                'unique_together': {('name', 'value')},
            },
        ),
    ]
