# Generated by Django 4.2.7 on 2023-11-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerfilegen', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockercommand',
            unique_together={('instruction', 'argument', 'variable')},
        ),
    ]
